repositories:
  # 添加新仓库示例
  # - owner: "microsoft"
  #   repo: "vscode-docs"
  #   branch: "main"
  #   files:
  #     - path: "docs/editor/basics.md"
  #       destination: "docs/tools/VSCode-Basics.md"
  #     - path: "docs/editor/debugging.md"
  #       destination: "docs/tools/VSCode-Debugging.md"
  - owner: "jaywcjlove"
    repo: "reference"
    branch: "main"
    files:
      # 编程语言
      - path: "docs/swift.md"
        destination: "docs/languages/Swift.md"
      - path: "docs/swiftui.md"
        destination: "docs/languages/SwiftUI.md"
      - path: "docs/typescript.md"
        destination: "docs/languages/TypeScript.md"
      - path: "docs/python.md"
        destination: "docs/languages/Python.md"
      - path: "docs/bash.md"
        destination: "docs/languages/Bash.md"
      - path: "docs/html.md"
        destination: "docs/languages/HTML.md"
      - path: "docs/css.md"
        destination: "docs/languages/CSS.md"

      # 框架
      - path: "docs/react.md"
        destination: "docs/frameworks/React.md"
      - path: "docs/nextjs.md"
        destination: "docs/frameworks/NextJS.md"
      - path: "docs/stylex.md"
        destination: "docs/frameworks/StyleX.md"

      # 工具
      - path: "docs/vim.md"
        destination: "docs/tools/Vim.md"
      - path: "docs/ffmpeg.md"
        destination: "docs/tools/FFmpeg.md"
      - path: "docs/latex.md"
        destination: "docs/tools/LaTeX.md"
      - path: "docs/git.md"
        destination: "docs/tools/Git.md"
      - path: "docs/github.md"
        destination: "docs/tools/GitHub.md"
      - path: "docs/github-actions.md"
        destination: "docs/tools/GitHub-Actions.md"
      - path: "docs/github-cli.md"
        destination: "docs/tools/GitHub-CLI.md"
      - path: "docs/github-copilot.md"
        destination: "docs/tools/GitHub-Copilot.md"
      - path: "docs/conda.md"
        destination: "docs/tools/Conda.md"
      - path: "docs/npm.md"
        destination: "docs/tools/NPM.md"
      - path: "docs/nvm.md"
        destination: "docs/tools/NVM.md"
      - path: "docs/openssl.md"
        destination: "docs/tools/OpenSSL.md"
      - path: "docs/pandoc.md"
        destination: "docs/tools/Pandoc.md"
      - path: "docs/ssh.md"
        destination: "docs/tools/SSH.md"
      - path: "docs/tar.md"
        destination: "docs/tools/Tar.md"
      - path: "docs/nginx.md"
        destination: "docs/tools/Nginx.md"
      - path: "docs/homebrew.md"
        destination: "docs/tools/Homebrew.md"
      - path: "docs/apt.md"
        destination: "docs/tools/APT.md"
      - path: "docs/curl.md"
        destination: "docs/tools/Curl.md"
      - path: "docs/sublime-text.md"
        destination: "docs/tools/Sublime-Text.md"
      - path: "docs/xcode.md"
        destination: "docs/tools/Xcode.md"
      - path: "docs/sketch.md"
        destination: "docs/tools/Sketch.md"

      # 数据库
      - path: "docs/mysql.md"
        destination: "docs/tools/MySQL.md"
      - path: "docs/sqlite.md"
        destination: "docs/tools/SQLite.md"
      - path: "docs/mongodb.md"
        destination: "docs/tools/MongoDB.md"
      - path: "docs/redis.md"
        destination: "docs/tools/Redis.md"

      # 格式和标准
      - path: "docs/markdown.md"
        destination: "docs/formats/Markdown.md"
      - path: "docs/ini.md"
        destination: "docs/formats/INI.md"
      - path: "docs/json.md"
        destination: "docs/formats/JSON.md"
      - path: "docs/yaml.md"
        destination: "docs/formats/YAML.md"
      - path: "docs/package.json.md"
        destination: "docs/formats/Package-JSON.md"

      # AI 相关
      - path: "docs/chatgpt.md"
        destination: "prompts/models/ChatGPT.md"

      # 参考资料
      - path: "docs/linux-command.md"
        destination: "docs/references/Linux-Command.md"
      - path: "docs/regex.md"
        destination: "docs/references/Regex.md"
      - path: "docs/quickreference.md"
        destination: "docs/references/Quick-Reference.md"
      - path: "docs/aspect-ratio.md"
        destination: "docs/references/Aspect-Ratio.md"
      - path: "docs/ascii-code.md"
        destination: "docs/references/ASCII-Code.md"
      - path: "docs/symbol-code.md"
        destination: "docs/references/Symbol-Code.md"
      - path: "docs/colors-named.md"
        destination: "docs/references/Colors-Named.md"
      - path: "docs/http-status-code.md"
        destination: "docs/references/HTTP-Status-Code.md"
      - path: "docs/html-char.md"
        destination: "docs/references/HTML-Char.md"
      - path: "docs/emoji.md"
        destination: "docs/references/Emoji.md"
      - path: "docs/resolutions.md"
        destination: "docs/references/Resolutions.md"
      - path: "docs/ports.md"
        destination: "docs/references/Ports.md"
